### ISSUE TITLE
Italicized items in puz format

### ISSUE THREAD

**Issue by arelkin** [jpd236/CrosswordScraper#11]
Mac/Firefox
Crossword Scraper Version: 1.2.5
Last Updated: January 30, 2022

https://www.mckinsey.com/featured-insights/the-mckinsey-crossword/march-1-2022

In puz format, italicized items are converted to quoted with old-fashioned quotes
those clues then have a blank double return after them.
14-Across, 9-Down, 20-Down, 28-Down, 37-Down, 58-Down
(see scan of physical printout from puz file)

Notice items that were quoted with fancy quotes, do not have the problem
8-Down

![PeterGordon-GoldilocksZone](https://user-images.githubusercontent.com/213207/156472110-9a08acff-47c3-4994-9589-a2b021832e08.jpg)

[PeterGordon-GoldilocksZone.puz.zip](https://github.com/jpd236/CrosswordScraper/files/8173778/PeterGordon-GoldilocksZone.puz.zip)

(I had to zip the puz, because Github wouldn't accept puz extension files.)

**Comment by jpd236** [comment]
The raw data includes these newlines. This is one of the original clues:

```
<i>Working Girl</i><span> star Griffith\n\n</span>
```

I guess the applet is trimming them. We can probably do the same, although there could be some edge cases here (maybe newlines in the middle of a clue are legitimate?)

**Comment by jpd236** [comment]
Will be fixed in the next release - thanks for the report!
