### ISSUE TITLE
FYI: strange title extraction on New Yorker puzzle

### ISSUE THREAD

**Issue by arelkin** [jpd236/CrosswordScraper#16]
https://www.newyorker.com/puzzles-and-games-dept/crossword/2022/07/22

![nyer-title-grab](https://user-images.githubusercontent.com/213207/180658837-c31050ad-a1b3-434a-a796-ba96dd1ba6d5.jpg)

**Comment by jpd236** [comment]
Thanks! I think this is fixed, but I'd like to see one or two more Friday New Yorker puzzle to see if this is handled correctly going forward before I make another release. Should be resolved in the next version.
