### ISSUE TITLE
Can't access options page

### ISSUE THREAD

**Issue by fncll** [jpd236/CrosswordScraper#19]
When I try to access the Crossword Scraper options, the page title loads, but has just a spinning circle as if it is waiting for something.

I do see this error in the console:

![CleanShot 2022-08-12 at 10 34 09@2x](https://user-images.githubusercontent.com/1208889/184412975-d9a6816d-865c-417b-8cda-c1c43cf399bc.png)

**Comment by jpd236** [comment]
Reproduced, thanks. Only seems to be happening with Manifest v2, not Manifest v3. I think I forgot to apply a fix to the options page HTML for that.
