### ISSUE TITLE
One odd puzzle fail

### ISSUE THREAD

**Issue by fncll** [jpd236/CrosswordScraper#20]
For whatever reason, while all the other puzzles I have tried are found by Crossword Scraper, this one is not:
https://www.washingtonexaminer.com/crossword-swallow-ones-words

**Comment by jpd236** [comment]
The iframe is at https://aws1.washingtonexaminer.com/embeds/crossword/2022-04-26.html, and the puzzle scrapes fine from there, so we probably just have to add aws1.washingtonexaminer.com to the list of known hosts [here](https://github.com/jpd236/CrosswordScraper/blob/main/src/main/kotlin/com/jeffpdavidson/crosswordscraper/sources/CrosswordCompilerSource.kt#L13). Other puzzles have been hosted on a different domain.
