### ISSUE TITLE
Feature request: support for Android

### ISSUE THREAD

**Issue by wanders78746** [jpd236/CrosswordScraper#22]
It would be great to have this great tool available on either Chrome or Firefox on Android.

**Comment by jpd236** [comment]
Chrome for Android doesn't support extensions. There are other Chromium-based browsers which do, but my general feeling is that there are too many unique flavors to try and support more browsers unless it's trivial to do so.

Firefox does, but currently limits the ability to install extensions to a small set of curated extensions, per https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/.

So I definitely see the use case for this, but I think some work will be needed from at least one of the browser vendors before there's reason enough to devote time into making the scraper work.

**Comment by wanders78746** [comment]
Jeff,

THANKS for looking into this. I use Firefox on Android, and knew that it supported some extensions. I didn’t know that they were curated.

Willie

Sent from Mail for Windows

**Comment by arelkin** [comment]
On the Andriod FF drop-down menu, there is an option to "Request Desktop site". I check that box, and then I can access ALL the Firefox plugins. I installed Crossword Scraper on FF-Android and I have been able to download all three formats: puz, jpz and pdf.

![ff-dropdown-menu](https://user-images.githubusercontent.com/213207/209983636-e2ecc949-a502-42d6-9cc4-83400a5fdb75.jpg)

**Comment by jpd236** [comment]
With the [announcement](https://blog.mozilla.org/addons/2023/11/28/open-extensions-on-firefox-for-android-debut-december-14-but-you-can-get-a-sneak-peek-today/) that Firefox is once again opening the door for any extension on the latest version of the app, I tried to see the current state of the world. It seems like we're able to successfully read/parse a puzzle from at least one page, but none of the links - both puzzle links as well as the "Save Debug Log" link - are working. That suggests the method I'm using to initiate a download of the puzzle data won't work for some reason, though I'm not sure why. I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1867717 on Firefox - hopefully that will be recognized as a bug, or at least I'll get some workaround, and we can see if that resolves the issue.

**Comment by jpd236** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1867717 is now fixed, and I've verified that basic functionality is working as expected on Android.

Some remaining issues, but no blockers I could see:

- PDF files fail to download (but other formats work fine). I filed a follow up at https://bugzilla.mozilla.org/show_bug.cgi?id=1877898. We could always just turn off PDF support on mobile until it is supported.
- The Settings button opens settings below the popup, so it looks like nothing is happening when you press it until you close the popup. I don't think this was happening for the "Report issue" link (which is a normal link) so maybe we can construct the settings link manually and launch it in a new tab instead. Though probably worth filing a bug for the `browser.runtime.openOptionsPage()` API as I'd expect that to open over the popup.

**Comment by jpd236** [comment]
Version 1.3.14 is now available at Mozilla Addons for Firefox for Android v124 and higher, currently in beta, and minus PDF support until they fix a browser issue with that format.

https://whattrainisitnow.com/calendar/ suggests this version of Firefox should go to the stable channel on March 19th.

**Comment by jpd236** [comment]
The fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1867717 was reverted due to a new crash so we're back to waiting for that to be fixed.

**Comment by jpd236** [comment]
Firefox v130 is now stable, and Crossword Scraper declares support for it, so it can be downloaded directly from https://addons.mozilla.org/en-US/firefox/addon/crossword-scraper/.

So I think we can close this out! If/when Chrome ever adds support for extensions, we'll track that separately.
