### ISSUE TITLE
PuzzleMe issues

### ISSUE THREAD

**Issue by randrzejh** [jpd236/CrosswordScraper#29]
Great plugin- last two days, having problems with embedded PuzzleMe windows.

Try https://fordhamobserver.com/71620/fun-and-games/wednesday-january-25/

or 

https://www.blackcrossword.com/

**Comment by jpd236** [comment]
Thanks for the report! Thankfully just a trivial update since the puzzle data was moved somewhere slightly different.

Fixed in 1.2.19, which has been uploaded to the Chrome and Firefox app stores. Firefox typically approves within minutes, and Chrome within 1-2 days, though this can vary.
