### ISSUE TITLE
Some failing NYT Acrostics

### ISSUE THREAD

**Issue by fncll** [jpd236/CrosswordScraper#31]
The following NYT Acrostics are failing for me:

- 2001-05-06
- 2005-08-21
- 2008-09-14
- 2014-05-04
- 2017-05-14
- 2017-09-03
- 2019-11-10
- 2020-03-01

Thanks!

**Comment by jpd236** [comment]
Fixed in https://github.com/jpd236/kotwords/commit/ffe2f7f04d16f1cb3b334820ac9892d0de1e4eeb, will release soon.
