### ISSUE TITLE
The Modern Crossword

### ISSUE THREAD

**Issue by boisvert42** [jpd236/CrosswordScraper#33]
Any thought to adding it? Its content is just available as a JPZ, and the URL is exposed in the Javascript on the site as
```
__NEXT_DATA__.props.pageProps.gameContent.gameLevelDataSets[0].files[0].url
```

https://www.puzzlesociety.com/crossword-puzzles/modern-crossword

**Comment by jpd236** [comment]
It should already be working (the link you posted works for me). Sometimes if the page fails to load the applet correctly, I have to refresh, but the scraper seems to be working fine. Is it not working for you?

**Comment by boisvert42** [comment]
Maybe i need to update to the latest version. I'll try again. Good to know
it already works!
