### ISSUE TITLE
Stopped working on The Week crossword puzzles

### ISSUE THREAD

**Issue by lobert** [jpd236/CrosswordScraper#39]
Stopped working on The Week crossword puzzles

**Comment by arelkin** [comment]
The Week seems to have changed their website design as well as something about their puzzle management.

**Comment by lobert** [comment]
Thanks for getting back to me.

**Comment by arelkin** [comment]
I look here:
[https://theweek.com/tag/magazine-puzzles](https://theweek.com/tag/magazine-puzzles)
and look for puzzles labeled "interactive"

I also look here:
[https://theweek.com/archive](https://theweek.com/archive)
and also search for "interactive"
Sometimes this "archive" has the latest interactive puzzle before the previous link (don't know why)

**Comment by lobert** [comment]
Thanks.

**Comment by jpd236** [comment]
Thanks again for the report. Will be fixed in the next release.
