### ISSUE TITLE
amuselabs back again

### ISSUE THREAD

**Issue by randrzejh** [jpd236/CrosswordScraper#40]
back to blocking you all over the place.

https://www.mckinsey.com/featured-insights/the-mckinsey-crossword/November-7-2023

plenty of examples, but this should do.

thanks always for such a good product. anything i can do to complain on your behalf to amuselabs, just let me know

**Comment by jpd236** [comment]
Thanks. I'm assuming you're on version 1.3.10. There's a fix in 1.3.11 which has been awaiting Chrome Web Store review for a couple of days. Hopefully that should go through soon. In the mean time, you can use Firefox (which has 1.3.11 available) or follow the steps at https://github.com/jpd236/CrosswordScraper/wiki/Troubleshooting#installing-a-custom-release to manually install 1.3.11 with Chrome until it is officially approved.

If you _are_ on 1.3.11 and still seeing issues, let me know. I've tested your link with the latest version and it's working for me.
