### ISSUE TITLE
Doesn't work on Firefox for Android?

### ISSUE THREAD

**Issue by gngp** [jpd236/CrosswordScraper#45]
Everything seems to work fine, I downloaded the extension as normal by switching to Desktop view. I go to a working puzzle, activate the extension, and the puzzle is there. However, clicking **PUZ**, **JPZ**, and **IPUZ** all seem to do nothing. I wouldn't know where the files get saved and I mostly likely can't access it with the new Android update limiting file access, so that _could_ be the issue?
I also cannot send the debug log as **Save Debug Log** also doesn't do anything.

**Comment by jpd236** [comment]
See https://github.com/jpd236/CrosswordScraper/issues/22. This is an issue with Firefox that I reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1867717.

The good news is it was just marked as fixed again a few days ago, targeting version 130. You could try on the nightly build (https://play.google.com/store/apps/details?id=org.mozilla.fenix&hl=en_US) to see if it works. I've made a note to check back when that release becomes stable, and if it is, I'll mark the extension as supporting Firefox for Android so it's available in the official store without having to do things like switch to Desktop view.
