### ISSUE TITLE
Support for crosswordr.com?

### ISSUE THREAD

**Issue by arelkin** [jpd236/CrosswordScraper#48]
https://crosswordr.com/

**Comment by jpd236** [comment]
Looks reasonably feasible. The site itself is heavily-compiled ReactJS so we probably can't pull the content from the local page, but 
we could replicate the network call the page is making to https://api.crosswordr.com/graphql in a way that would hopefully be durable.

**Comment by jpd236** [comment]
Added an initial cut of this in version 1.3.19.

Scraping subscription-only doesn't work, and doesn't seem to have an easy path forward to supporting. But I think both of the currently-supported subscriptions are also distributed directly as downloadable files, so this doesn't seem like a huge deal.

There are probably also some quirks to be worked out as I don't know how their data representation handles certain cases that I wasn't able to find in a few example puzzles. These can be addressed as they are discovered.
